
quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver: org.h2.Driver
    username: sa
    password: ""
    # 최대 커넥션 수 설정
  smallrye-openapi:
    path: /swagger
  # Hibernate 설정 (JPA 사용 시)
  hibernate-orm:
    dialect: org.hibernate.dialect.H2Dialect
    log:
      sql: true
    database:
      generation: drop-and-create

